name: Installer job

on:
  workflow_dispatch:

jobs:
  run_long_running:
    name: "Installer job"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # prepare tgz
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - run: go version
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: mvn --version
      - name: Setup `packer`
        uses: hashicorp/setup-packer@v3.0.0
        id: setup
      - run: packer version
      # launch
      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3
      - run: python3 --version
      - run: pip3 list
      - run: terraform version
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy.yaml
          # Optional, directory where playbooks live
          directory: ./ansible
      - run: ansible --version
      # installer kos
      # check others
      - run: python3 --version
      - run: aws --version