# This is a basic workflow to help you get started with Actions

name: Multi CI Job

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job-1:
    runs-on: ubuntu-22.04
    steps:
      - name: test env
        run: |
          echo "hello world"
        shell: bash
      - name: test fail
        run: |
          exit 1
        shell: bash
      - name: test after fail
        run: |
          echo "hello world2"
        shell: bash
        if: ${{ always() }}
  job-2:
    runs-on: ubuntu-22.04
    steps:
      - name: test env
        run: |
          echo "hello world"
        shell: bash
      - name: test fail
        run: |
          exit 1
        shell: bash
      - name: test after fail
        run: |
          echo "hello world2"
        shell: bash
        if: ${{ always() }}
  summary:
    runs-on: ubuntu-22.04
    needs: [job-1, job-2]
    if: ${{ always() }}
    steps:
      - name: echo results
        run: |
          echo "job1:${{ needs.job-1.result }}, job2:${{ needs.job-2.result }}"
        shell: bash
