on: 
  workflow_dispatch:
  push:

jobs:
  job1:
    name: "1. call workflow in remote repo"
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      test-name: "base test"
    secrets:
      web_hook: ${{ secrets.WEB_HOOK_URL }}
  job2:
    name: "2. call workflow in local repo"
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      test-name: "futher test"
    secrets:
      web_hook: ${{ secrets.WEB_HOOK_URL }}
  summary:
    name: "summary jobs"
    runs-on: ubuntu-22.04
    needs: [job1, job2]
    steps:
      - name: show success
        run: echo "success"
        shell: bash
      - name: Collect build result
        run: |
          echo job1-${{ needs.job1.result }},job2-${{ needs.job2.result }}