on: 
  workflow_dispatch:
  push:

jobs:
  job1:
    name: "1. call workflow in remote repo"
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      test-name: "base test"
  job2:
    name: "2. call workflow in local repo"
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      test-name: "futher test"
      